### ISSUE TITLE
Crate Delight tries to load recipes with ingredients that don't exist

### ISSUE THREAD

**Issue by Sirfirelord1** [axperty/cratedelight-forge#3]
When mods such as Create are not in the pack, it tries to load those recipes for create compat anyway, causing an error (non-crash)
Minor error but it seems to be missing a check for what other mods are in the pack

**Comment by axperty** [comment]
Hi Sirfirelord1,

I'll make it load the recipe if the mod is loaded, seems like I forgot to add that. If you have any other errors, please let me know. 
A minor update will be released to fix this.

Have a good day, 
Axperty.

**Comment by Sirfirelord1** [comment]
Thanks for the fast response. Did some more looking through error logs and it appears that the same thing happens for More Delight (Forge) and possibly Storage Delight (not sure) - but i couldn't find a github for either of those linked, so I'm just following up here. Thanks for the great mods, by the way, we're using all 3 in our modpack <3

**Comment by axperty** [comment]
I think it might happen in More Delight, but I'm not really sure, because I recently added recipe conditions there.
I'm also working on having all mod versions on GitHub so it's easier to see the source code.

Thank you for using my mods, it means a lot, and I really appreciate it!

**Comment by Sirfirelord1** [comment]
Next time i see the error in console, i'll copy-paste it here if that helps!

**Comment by axperty** [comment]
Hi Sirfirelord1,

I recently submitted an update for Crate Delight addressing this issue, it should be fixed for now. The only thing is that I noticed it's not working on 1.20, but if you're playing 1.20.1 or 1.20.2, you won't have any issues.

Have a good day,
Axperty.

**Comment by pajicadvance** [comment]
This is still happening in the latest version for Fabric 1.21 (24.08.09). I don't think it's fixed.

https://mclo.gs/McF1MNY
